# Generated by Django 3.2.4 on 2021-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftprofile',
            name='receives_new_ticket_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
