# Generated by Django 3.2.4 on 2021-07-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_microsoftprofile_receives_new_ticket_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftprofile',
            name='teams_notifications_active',
            field=models.BooleanField(default=True),
        ),
    ]
