# Generated by Django 3.2.4 on 2021-07-29 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_microsoftprofile_teams_notifications_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftprofile',
            name='ms_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Microsoft ID'),
        ),
        migrations.AlterField(
            model_name='microsoftprofile',
            name='receives_new_ticket_notifications',
            field=models.BooleanField(default=False, verbose_name='Neues Ticket Benachrichtigungen aktiviert'),
        ),
        migrations.AlterField(
            model_name='microsoftprofile',
            name='teams_notifications_active',
            field=models.BooleanField(default=True, verbose_name='Benachrichtigungen aktiviert'),
        ),
        migrations.AlterField(
            model_name='microsoftprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
