# Generated by Django 3.2.4 on 2021-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210729_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftprofile',
            name='dark_mode_active',
            field=models.BooleanField(default=False),
        ),
    ]
