# Generated by Django 3.2.4 on 2021-09-21 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210920_1649'),
        ('authentication', '0006_auto_20210921_0750'),
    ]

    operations = [
    ]
