# Generated by Django 3.2.4 on 2021-09-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_microsoftprofile_last_inactive_ticket_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microsoftprofile',
            name='last_inactive_ticket_reminder',
        ),
    ]
